
// Generated by https://quicktype.io
export interface FetchAllArticleResponse {
    results:  ArticlesSearch[];
}

export interface ArticlesSearch {
    idArticulo: string
    arNombre: string;
    arDescripcion:  string;
    movement: string;
}


export interface Article {
    name: any;
    idArticulo: string;
    arNombre: string;
    arDescripcion: string;
    movement: string;
}

